### ISSUE TITLE
hosting

### ISSUE THREAD

**Issue by rezarffahlevi** [ahmdilhaam/01_praktikum_php#1]
tugas kuliah harusnya dihosting juga wkwk

**Comment by ahmdilhaam** [comment]
boleh kak sponsor/endorse nya hosting

**Comment by ahmdilhaam** [comment]
> tugas kuliah harusnya dihosting juga wkwk

boleh kak sponsor/endorse nya hosting

**Comment by rezarffahlevi** [comment]
https://firebase.google.com/
